routes/web.php
<?php

use App\Http\Controllers\Admin_Panel\AuthController;
use App\Models\Admin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth:admin'])->name('dashboard');

//
//require __DIR__.'/auth.php';
//Route::get('/clear-cache', function() {
//    $exitCode = Artisan::call('cache:clear');
//    // return what you want
//});
/*
|--------------------------------------------------------------------------
| Admin Authentication
|--------------------------------------------------------------------------
*/


Route::group(['prefix' => 'admin_panel','as' => 'admin_panel.'], function () {
//    Route::post('/register', [AuthController::class, 'register']);
    Route::get('/login_view', [AuthController::class, 'loginView'])->name('login');
    Route::post('/login', [AuthController::class, 'login']);

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', [AuthController::class, 'analys']);
        Route::resource('profile', AuthController::class);
        Route::get('/edit_password', [AuthController::class, 'editPassword']);
        Route::post('/update_password', [AuthController::class, 'updatePassword']);
        Route::get('/logout', [AuthController::class, 'logout']);

        ## Resturant Routes
        Route::resource('resturants', \App\Http\Controllers\Admin_Panel\ResturantController::class);
        Route::get('/resturant_del/{id}', [\App\Http\Controllers\Admin_Panel\ResturantController::class, 'destroy']);
        Route::get('/search_resturant/{id}',[\App\Http\Controllers\Admin_Panel\ResturantController::class,'search']);
        Route::get('/reject/{id}',[\App\Http\Controllers\Admin_Panel\ResturantController::class,'reject']);
        Route::get('/accept/{id}',[\App\Http\Controllers\Admin_Panel\ResturantController::class,'accept']);


        ## Representative Routes
        Route::resource('representatives', \App\Http\Controllers\Admin_Panel\RepresentativeController::class);
        Route::get('/representative_del/{id}', [\App\Http\Controllers\Admin_Panel\RepresentativeController::class, 'destroy']);
        Route::get('/search_representative',[\App\Http\Controllers\Admin_Panel\RepresentativeController::class,'search']);

        ## Client Routes
        Route::resource('clients', \App\Http\Controllers\Admin_Panel\ClientController::class);
        Route::get('/client_del/{id}', [\App\Http\Controllers\Admin_Panel\ClientController::class, 'destroy']);
        Route::get('/client_orders/{id}', [\App\Http\Controllers\Admin_Panel\ClientController::class, 'orders']);
        Route::get('/client_rates/{id}', [\App\Http\Controllers\Admin_Panel\ClientController::class, 'rates']);
        Route::get('/search_client',[\App\Http\Controllers\Admin_Panel\ClientController::class,'search']);

        ## Advisor Routes
        Route::resource('advisors', \App\Http\Controllers\Admin_Panel\AdvisorController::class);
        Route::get('/advisor_del/{id}', [\App\Http\Controllers\Admin_Panel\AdvisorController::class, 'destroy']);
        Route::get('/search_advisor',[\App\Http\Controllers\Admin_Panel\AdvisorController::class,'search']);

        ## Setting Routes
        Route::resource('settings', \App\Http\Controllers\Admin_Panel\SettingController::class);

        ## Coupon Routes
        Route::resource('coupons', \App\Http\Controllers\Admin_Panel\CouponController::class);
        Route::get('/coupon_del/{id}', [\App\Http\Controllers\Admin_Panel\CouponController::class, 'destroy']);
        Route::get('/search_coupon',[\App\Http\Controllers\Admin_Panel\CouponController::class,'search']);

        ## Meal Types Routes
        Route::resource('meal_types', \App\Http\Controllers\Admin_Panel\MealTypeController::class);
        Route::get('/meal_type_del/{id}', [\App\Http\Controllers\Admin_Panel\MealTypeController::class, 'destroy']);
        Route::get('/search_meal_type',[\App\Http\Controllers\Admin_Panel\MealTypeController::class,'search']);
        Route::get('/reject_meal_type/{id}',[\App\Http\Controllers\Admin_Panel\MealTypeController::class,'reject']);
        Route::get('/accept_meal_type/{id}',[\App\Http\Controllers\Admin_Panel\MealTypeController::class,'accept']);

    });
});


Route::get('/token', function () {
    return csrf_token();
});

app/Http/Controllers/Admin_Panel/ClientController.php
<?php

namespace App\Http\Controllers\Admin_Panel;

use App\Http\Controllers\Controller;
use App\Http\Traits\SaveImageTrait;
use App\Models\Admin;
use App\Models\City;
use App\Models\Client;
use App\Models\MealRating;
use App\Models\Order;
use App\Models\PackageRating;
use App\Models\Rating;
use App\Models\ResturantRating;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

class ClientController extends Controller
{
    use SaveImageTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $admin=auth('admin')->user();
        $clients=Client::orderBy('created_at', 'DESC')->paginate(15);
        return view('admin.clients.index',['admin'=>$admin,'clients'=>$clients]);
    }

    public function search(Request $request)
    {
        if($request->ajax())
        {
            $output="";
            $clients=Client::where('name','LIKE','%'.$request->search."%")
                             ->orWhere('email','LIKE','%'.$request->search."%")->orderBy('created_at', 'DESC')->get();
            if($clients)
            {$counter=1;
            $output.='  <table id="myTable1" class="table table-striped table-bordered table-sm">
                <thead>
                <tr>
                    <th class="text-center" scope="col"></th>
                    <th scope="col">اسم العميل</th>
                    <th scope="col">تاريخ الانضمام</th>
                    <th class="text-center" scope="col"></th>
                </tr>
                </thead>
                <tbody>';
                foreach ($clients as $key => $client) {
                    $output.='<tr>
                          <td>
                            <p class="text-center">'.$counter.'</p>
                            <span class="text-success"></span>
                        </td>
                        <td>
                            <div class="media">
                                <div class="avatar me-2">
                                    <img alt="avatar" src="/'.$client->personal_image.'" class="rounded-circle" />
                                </div>
                                <div class="media-body align-self-center">
                                    <h6 class="mb-0">'.$client->name.'</h6>
                                    <span>'.$client->email.'</span>
                                </div>
                            </div>
                        </td>
                        <td>
                            <p class="mb-0">'.$client->created_at->toDateString().'</p>
                            <span class="text-success"></span>
                        </td>
                        <td class="text-center">
                            <div class="action-btns">
                                <a href="'.route('admin_panel.clients.show',$client->id).'" class="action-btn btn-view bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="عرض">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
                                </a>
                                <a href="'.route('admin_panel.clients.edit',$client->id).'" class="action-btn btn-edit bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="تعديل">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg>
                                </a>
                                <a href="/admin_panel/client_orders/'.$client->id.'" class="action-btn btn-view bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="الطلبات">
                                    <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clipboard"><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"></path><rect x="8" y="2" width="8" height="4" rx="1" ry="1"></rect></svg>
                                </a>
                                <a href="/admin_panel/client_rates/'.$client->id.'" class="action-btn btn-view bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="التقييمات">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-award" viewBox="0 0 16 16"><path d="M9.669.864 8 0 6.331.864l-1.858.282-.842 1.68-1.337 1.32L2.6 6l-.306 1.854 1.337 1.32.842 1.68 1.858.282L8 12l1.669-.864 1.858-.282.842-1.68 1.337-1.32L13.4 6l.306-1.854-1.337-1.32-.842-1.68L9.669.864zm1.196 1.193.684 1.365 1.086 1.072L12.387 6l.248 1.506-1.086 1.072-.684 1.365-1.51.229L8 10.874l-1.355-.702-1.51-.229-.684-1.365-1.086-1.072L3.614 6l-.25-1.506 1.087-1.072.684-1.365 1.51-.229L8 1.126l1.356.702 1.509.229z"/><path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/></svg>
                                </a>
                                <a href="/admin_panel/client_del/'.$client->id.'" class="action-btn btn-delete bs-tooltip" data-toggle="tooltip" data-placement="top" title="حذف">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                </a>
                            </div>
                        </td>'.
                        '</tr>';
$counter++;
                }
                $output.='     </tbody>

            </table>
            <div class="row">
                <div class="col-sm-12 col-md-5">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">

                    </div>
                </div>
                <div class="col-sm-12 col-md-7">

                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">

                      

                    </div>
                </div>
            </div>
             <script>

            addPagerToTables(\'#myTable1\', 4);

            function addPagerToTables(tables, rowsPerPage = 10) {

                tables =
                    typeof tables == "string"
                        ? document.querySelectorAll(tables)
                        : tables;

                for (let table of tables)
                    addPagerToTable(table, rowsPerPage);

            }

            function addPagerToTable(table, rowsPerPage = 10) {

                let tBodyRows = getBodyRows(table);
                let numPages = Math.ceil(tBodyRows.length/rowsPerPage);

                let colCount =
                    [].slice.call(
                        table.querySelector(\'tr\').cells
                    )
                        .reduce((a,b) => a + parseInt(b.colSpan), 0);

                table
                    .createTFoot()
                    .insertRow()
                    .innerHTML = `<td colspan=${colCount}><div class="nav"></div></td>`;

                if(numPages == 1)
                    return;

                for(i = 0;i < numPages;i++) {

                    let pageNum = i + 1;

                    table.querySelector(\'.nav\')
                        .insertAdjacentHTML(
                            \'beforeend\',
                            `<a href="#" rel="${i}">${pageNum}</a> `
                        );

                }

                changeToPage(table, 1, rowsPerPage);

                for (let navA of table.querySelectorAll(\'.nav a\'))
                    navA.addEventListener(
                        \'click\',
                        e => changeToPage(
                            table,
                            parseInt(e.target.innerHTML),
                            rowsPerPage
                        )
                    );

            }

            function changeToPage(table, page, rowsPerPage) {

                let startItem = (page - 1) * rowsPerPage;
                let endItem = startItem + rowsPerPage;
                let navAs = table.querySelectorAll(\'.nav a\');
                let tBodyRows = getBodyRows(table);

                for (let nix = 0; nix < navAs.length; nix++) {

                    if (nix == page - 1)
                        navAs[nix].classList.add(\'active\');
                    else
                        navAs[nix].classList.remove(\'active\');

                    for (let trix = 0; trix < tBodyRows.length; trix++)
                        tBodyRows[trix].style.display =
                            (trix >= startItem && trix < endItem)
                                ? \'table-row\'
                                : \'none\';

                }

            }

            // tbody might still capture header rows if
            // if a thead was not created explicitly.
            // This filters those rows out.
            function getBodyRows(table) {
                let initial = table.querySelectorAll(\'tbody tr\');
                return Array.from(initial)

app/Http/Controllers/Api/Client/AddressController.php
<?php

namespace App\Http\Controllers\Api\Client;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\Client_App\Address\StoreAddressRequest;
use App\Http\Requests\Api\Client_App\Address\UpdateAddressRequest;
use App\Http\Resources\Api\Client_App\Address\AddressResource;
use App\Http\Traits\ApiResponseTrait;
use App\Http\Traits\SaveImageTrait;
use App\Models\Address;
use Illuminate\Http\Request;

class AddressController extends Controller
{
    use  ApiResponseTrait;
    public function index(Request $request)
    {
        $client = $request->user('client_api');
        $addresses = Address::where('client_id', $client->id)->orderBy('created_at', 'DESC')->get();
        return $this->apiResponse(AddressResource::collection($addresses), 'All Addresses ', 200);
    }


    public function store(StoreAddressRequest $request)
    {
        $client = $request->user('client_api');
        $address=Address::create([
            'client_id'    =>$client->id,
            'name'         =>$request->name,
            'location'     =>$request->location,
            'latitude'      =>$request->latitude,
            'longitude'     =>$request->longitude
        ]);
        return $this->apiResponse(new AddressResource($address), 'The address has been created successfully', 200);
    }



    public function update(UpdateAddressRequest $request, $id)
    {
        $client = $request->user('client_api');
        $address=Address::find($id);

        $address->update([
            'client_id'    =>$client->id,
            'name'         =>$request->name,
            'location'     =>$request->location,
            'latitude'      =>$request->latitude,
            'longitude'     =>$request->longitude
        ]);

        return $this->apiResponse(new AddressResource($address), 'The address has been updated successfully', 200);
    }


    public function destroy($id)
    {
        $address=Address::find($id);
        $address->delete();
        return $this->apiResponse(null, 'The address has been deleted successfully', 200);
    }
    public function SetAsMain(Request $request, $id)
    {
        $client = $request->user('client_api');
        $old=Address::where('status','1')->where('client_id',$client->id)->first();
        if($old){
            $old->update(['status' => '2']);
        }

        $address=Address::find($id);
        $address->update(['status' => '1']);

        return $this->apiResponse(null, 'The address has been set as main successfully', 200);
    }
    public function getMain(Request $request)
    {
        $client = $request->user('client_api');
        $main=Address::where('status','1')->where('client_id',$client->id)->first();

        return $this->apiResponse(new AddressResource($main), 'The main address of client', 200);
    }

}

resources/views/admin/clients/edit.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item">العملاء </li>
                                    <li class="breadcrumb-item active"> تعديل العميل </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class="">تعديل معلومات العميل</h3>
                        </div>

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                <form class=" g-3" method="post" action="{{route('admin_panel.clients.update',$client->id)}}" enctype="multipart/form-data" >
                                    @method('PATCH')
                                    @csrf
                                    @if ($errors->any())

                                        <div class="alert alert-danger">

                                            <ul style="list-style: none;margin:0">

                                                @foreach ($errors->all() as $error)

                                                    <li>{{ $error }}</li>

                                                @endforeach

                                            </ul>

                                        </div>

                                    @endif
                                    <div class="col-md-6">
{{--                                        <label for="inputAddress" class="form-label"> الصورة الشخصية </label>--}}
                                        <img alt="avatar" src="/{{$client->personal_image}}"  width="200" height="200"/>
                                        <br><br>
                                        <input type="file" class="form-control"  placeholder="1234 Main St" name="personal_image">
                                    </div>


                                    <div class="col-md-6">
                                        <label for="inputEmail4" class="form-label">الاسم </label>
                                        <input type="text" class="form-control"  value="{{$client->name}}" name="name">
                                    </div>
                                    <div class="col-md-6">
                                        <label for="inputEmail4" class="form-label">البريد الالكتروني</label>
                                        <input type="email" class="form-control"  value="{{$client->email}}" name="email">
                                    </div>
                                    <div class="col-md-6">
                                        <label for="inputEmail4" class="form-label">رقم الجوال</label>
                                        <input type="tel" class="form-control"  value="{{$client->mobile}}" name="mobile">
                                    </div>

                                    <div class="col-md-6">
                                        <label for="inputState" class="form-label">المدينة</label>
                                        <select class="form-select" name="city_id">
                                            <option selected value="{{$client->city->id}}">{{$client->city->translate('ar')->name}} </option>
                                            @foreach($cities as $city)
                                                @if($city->id != $client->city->id)
                                                    <option value="{{$city->id}}">{{$city->translate('ar')->name}}</option>
                                                @endif
                                            @endforeach
                                        </select>
                                    </div>

                                    <div class="col-6">
                                        <div class="text-center">
                                        <button type="submit" class="btn btn-primary">تعديل</button>
                                        </div>
                                    </div>


                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/clients/item.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item">العملاء </li>
                                    <li class="breadcrumb-item active"> عرض العميل </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class=""> معلومات العميل</h3>
                        </div>

                        <div class="" style="padding:0px 2%; font-weight: bold;">
                            <div class="container">
                                <div class="col-md-6">
                                    <div class="col-md-6 ">
{{--                                        <label for="inputAddress" class="form-label "> الصورة الشخصية </label>--}}
                                        <img alt="avatar" src="/{{$client->personal_image}}"  width="200" height="200"/>
                                        <br><br>
                                    </div>

                                    <div class="col-md-6">
                                        <label for="inputEmail4" class="form-label">البريد الالكتروني : </label>
                                        @if($client->email)
                                            <span>{{$client->email}}</span>
                                        @else
                                           <span> لا يوجد</span>
                                        @endif
                                    </div>

                                    <div class="col-md-6">
                                        <label for="inputEmail4" class="form-label">رقم الجوال : </label>
                                        <span>{{$client->mobile}}</span>
                                    </div>

                                    <div class="col-md-6">
                                        <label for="inputEmail4" class="form-label">الاسم : </label>
                                        <span>{{$client->name}}</span>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="inputState" class="form-label">المدينة : </label>
                                        <span>{{$client->city->translate('ar')->name}}</span>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{{--        <div class="container">--}}

{{--            <div class="col-md-6">--}}
{{--                    <div class="col-md-6">--}}
{{--                        <label for="inputAddress" class="form-label"> الصورة الشخصية </label>--}}
{{--                        <img alt="avatar" src="/{{$client->personal_image}}"  width="200" height="200"/>--}}
{{--                        <br><br>--}}
{{--                    </div>--}}

{{--                    <div class="col-md-6">--}}
{{--                        <label for="inputEmail4" class="form-label">البريد الالكتروني</label>--}}
{{--                        @if($client->email)--}}
{{--                             <p>{{$client->email}}</p>--}}
{{--                        @else--}}
{{--                        لا يوجد--}}
{{--                        @endif--}}
{{--                    </div>--}}

{{--                    <div class="col-md-6">--}}
{{--                        <label for="inputEmail4" class="form-label">رقم الجوال</label>--}}
{{--                        <p>{{$client->mobile}}</p>--}}
{{--                    </div>--}}

{{--                    <div class="col-md-6">--}}
{{--                        <label for="inputEmail4" class="form-label">الاسم </label>--}}
{{--                        <p>{{$client->name}}</p>--}}
{{--                    </div>--}}
{{--                <div class="col-md-6">--}}
{{--                    <label for="inputState" class="form-label">المدينة</label>--}}
{{--                    <p>{{$client->city->translate('ar')->name}}</p>--}}
{{--                </div>--}}
{{--            </div>--}}

{{--        </div>--}}
        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection