routes/web.php
<?php

use App\Http\Controllers\Admin_Panel\AuthController;
use App\Models\Admin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth:admin'])->name('dashboard');

//
//require __DIR__.'/auth.php';
//Route::get('/clear-cache', function() {
//    $exitCode = Artisan::call('cache:clear');
//    // return what you want
//});
/*
|--------------------------------------------------------------------------
| Admin Authentication
|--------------------------------------------------------------------------
*/


Route::group(['prefix' => 'admin_panel','as' => 'admin_panel.'], function () {
//    Route::post('/register', [AuthController::class, 'register']);
    Route::get('/login_view', [AuthController::class, 'loginView'])->name('login');
    Route::post('/login', [AuthController::class, 'login']);

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', [AuthController::class, 'analys']);
        Route::resource('profile', AuthController::class);
        Route::get('/edit_password', [AuthController::class, 'editPassword']);
        Route::post('/update_password', [AuthController::class, 'updatePassword']);
        Route::get('/logout', [AuthController::class, 'logout']);

        ## Resturant Routes
        Route::resource('resturants', \App\Http\Controllers\Admin_Panel\ResturantController::class);
        Route::get('/resturant_del/{id}', [\App\Http\Controllers\Admin_Panel\ResturantController::class, 'destroy']);
        Route::get('/search_resturant/{id}',[\App\Http\Controllers\Admin_Panel\ResturantController::class,'search']);
        Route::get('/reject/{id}',[\App\Http\Controllers\Admin_Panel\ResturantController::class,'reject']);
        Route::get('/accept/{id}',[\App\Http\Controllers\Admin_Panel\ResturantController::class,'accept']);


        ## Representative Routes
        Route::resource('representatives', \App\Http\Controllers\Admin_Panel\RepresentativeController::class);
        Route::get('/representative_del/{id}', [\App\Http\Controllers\Admin_Panel\RepresentativeController::class, 'destroy']);
        Route::get('/search_representative',[\App\Http\Controllers\Admin_Panel\RepresentativeController::class,'search']);

        ## Client Routes
        Route::resource('clients', \App\Http\Controllers\Admin_Panel\ClientController::class);
        Route::get('/client_del/{id}', [\App\Http\Controllers\Admin_Panel\ClientController::class, 'destroy']);
        Route::get('/client_orders/{id}', [\App\Http\Controllers\Admin_Panel\ClientController::class, 'orders']);
        Route::get('/client_rates/{id}', [\App\Http\Controllers\Admin_Panel\ClientController::class, 'rates']);
        Route::get('/search_client',[\App\Http\Controllers\Admin_Panel\ClientController::class,'search']);

        ## Advisor Routes
        Route::resource('advisors', \App\Http\Controllers\Admin_Panel\AdvisorController::class);
        Route::get('/advisor_del/{id}', [\App\Http\Controllers\Admin_Panel\AdvisorController::class, 'destroy']);
        Route::get('/search_advisor',[\App\Http\Controllers\Admin_Panel\AdvisorController::class,'search']);

        ## Setting Routes
        Route::resource('settings', \App\Http\Controllers\Admin_Panel\SettingController::class);

        ## Coupon Routes
        Route::resource('coupons', \App\Http\Controllers\Admin_Panel\CouponController::class);
        Route::get('/coupon_del/{id}', [\App\Http\Controllers\Admin_Panel\CouponController::class, 'destroy']);
        Route::get('/search_coupon',[\App\Http\Controllers\Admin_Panel\CouponController::class,'search']);

        ## Meal Types Routes
        Route::resource('meal_types', \App\Http\Controllers\Admin_Panel\MealTypeController::class);
        Route::get('/meal_type_del/{id}', [\App\Http\Controllers\Admin_Panel\MealTypeController::class, 'destroy']);
        Route::get('/search_meal_type',[\App\Http\Controllers\Admin_Panel\MealTypeController::class,'search']);
        Route::get('/reject_meal_type/{id}',[\App\Http\Controllers\Admin_Panel\MealTypeController::class,'reject']);
        Route::get('/accept_meal_type/{id}',[\App\Http\Controllers\Admin_Panel\MealTypeController::class,'accept']);

    });
});


Route::get('/token', function () {
    return csrf_token();
});

app/Models/Advisor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Advisor extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'mobile','personal_image','description'];
}

app/Http/Controllers/Admin_Panel/AdvisorController.php
<?php

namespace App\Http\Controllers\Admin_Panel;

use App\Http\Controllers\Controller;
use App\Http\Traits\SaveImageTrait;
use App\Models\Admin;
use App\Models\Advisor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class AdvisorController extends Controller
{
    use SaveImageTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $admin=auth('admin')->user();
        $advisors=Advisor::orderBy('created_at', 'DESC')->paginate(15);
        return view('admin.advisors.index',['admin'=>$admin,'advisors'=>$advisors]);
    }

    public function search(Request $request)
    {
        if($request->ajax())
        {
            $output="";
            $advisors=Advisor::where('name','LIKE','%'.$request->search."%")->orderBy('created_at', 'DESC')->get();
            if($advisors)
            {$counter=1;
            $output.='  <table id="myTable1" class="table table-striped table-bordered table-sm">
                <thead>
                <tr>
                    <th class="text-center" scope="col"></th>
                    <th scope="col">اسم المستشار</th>
                    <th scope="col">تاريخ الانضمام</th>
                    <th class="text-center" scope="col"></th>
                </tr>
                </thead>
                <tbody>';
                foreach ($advisors as $key => $advisor) {
                    $output.='<tr>
                        <td>
                            <p class="text-center">'.$counter.'</p>
                            <span class="text-success"></span>
                        </td>
                        <td>
                            <div class="media">
                                <div class="avatar me-2">
                                    <img alt="avatar" src="/'.$advisor->personal_image.'" class="rounded-circle" />
                                </div>
                                <div class="media-body align-self-center">
                                    <h6 class="mb-0">'.$advisor->name.'</h6>
                                 
                                </div>
                            </div>
                        </td>
                        <td>
                            <p class="mb-0">'.$advisor->created_at->toDateString().'</p>
                            <span class="text-success"></span>
                        </td>
                        <td class="text-center">
                            <div class="action-btns">
                                <a href="'.route('admin_panel.advisors.show',$advisor->id).'" class="action-btn btn-view bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="عرض">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
                                </a>  
                                <a href="'.route('admin_panel.advisors.edit',$advisor->id).'" class="action-btn btn-edit bs-tooltip me-2" data-toggle="tooltip" data-placement="top" title="تعديل">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg>
                                </a>                 
                                <a href="/admin_panel/client_del/'.$advisor->id.'" class="action-btn btn-delete bs-tooltip" data-toggle="tooltip" data-placement="top" title="حذف">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                </a>
                            </div>
                        </td>'.
                        '</tr>';
                    $counter++;
                }
                $output.='           </tbody>

            </table>
            <a class="btn btn-primary mb-2 me-4" href="{{route(\'admin_panel.advisors.create\')}}">إضافة مستشار </a>

            <div class="row">
                <div class="col-sm-12 col-md-5">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">

                    </div>
                </div>
                <div class="col-sm-12 col-md-7">

                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">

                     

                    </div>
                </div>
            </div>

   <script>

            addPagerToTables(\'#myTable1\', 4);

            function addPagerToTables(tables, rowsPerPage = 10) {

                tables =
                    typeof tables == "string"
                        ? document.querySelectorAll(tables)
                        : tables;

                for (let table of tables)
                    addPagerToTable(table, rowsPerPage);

            }

            function addPagerToTable(table, rowsPerPage = 10) {

                let tBodyRows = getBodyRows(table);
                let numPages = Math.ceil(tBodyRows.length/rowsPerPage);

                let colCount =
                    [].slice.call(
                        table.querySelector(\'tr\').cells
                    )
                        .reduce((a,b) => a + parseInt(b.colSpan), 0);

                table
                    .createTFoot()
                    .insertRow()
                    .innerHTML = `<td colspan=${colCount}><div class="nav"></div></td>`;

                if(numPages == 1)
                    return;

                for(i = 0;i < numPages;i++) {

                    let pageNum = i + 1;

                    table.querySelector(\'.nav\')
                        .insertAdjacentHTML(
                            \'beforeend\',
                            `<a href="#" rel="${i}">${pageNum}</a> `
                        );

                }

                changeToPage(table, 1, rowsPerPage);

                for (let navA of table.querySelectorAll(\'.nav a\'))
                    navA.addEventListener(
                        \'click\',
                        e => changeToPage(
                            table,
                            parseInt(e.target.innerHTML),
                            rowsPerPage
                        )
                    );

            }

            function changeToPage(table, page, rowsPerPage) {

                let startItem = (page - 1) * rowsPerPage;
                let endItem = startItem + rowsPerPage;
                let navAs = table.querySelectorAll(\'.nav a\');
                let tBodyRows = getBodyRows(table);

                for (let nix = 0; nix < navAs.length; nix++) {

                    if (nix == page - 1)
                        navAs[nix].classList.add(\'active\');
                    else
                        navAs[nix].classList.remove(\'active\');

                    for (let trix = 0; trix < tBodyRows.length; trix++)
                        tBodyRows[trix].style.display =
                            (trix >= startItem && trix < endItem)
                                ? \'table-row\'
                                : \'none\';

                }

            }

            // tbody might still capture header rows if
            // if a thead was not created explicitly.
            // This filters those rows out.
            function getBodyRows(table) {
                let initial = table.querySelectorAll(\'tbody tr\');
                return Array.from(initial)
                    .filter(row => row.querySelectorAll(\'td\').length > 0);
            }
        </script>';
                return Response($output);
            }
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $admin=auth('admin')->user();
        return view('admin.advisors.create',['admin'=>$admin]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $admin=auth('admin')->user();
        try {
            $advisor = Advisor::create([
                'name' => $request->name,
                'mobile' => $request->mobile,
                'description' => $request->description
            ]);
            if ($request->file('personal_image')) {
                $advisor->update([
                    'personal_image' => $this->saveImage($request->file('personal_image'), 'Images/Advisors', 400, 400),
                ]);
            }
        }catch (\Exception $e) { // It's actually a QueryException but this works too
            if ($e->getCode() == 23000) {
                return  redirect()->back()->withErrors(['msg' => 'رقم الجوال تم اخذه مسبقا  ']);
            }
        }
        return redirect(route('admin_panel.advisors.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $admin=auth('admin')->user();
        $advisor=Advisor::find($id);

resources/views/admin/advisors/create.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item">المستشارين</li>
                                    <li class="breadcrumb-item active"> إضافة </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class="">إضافة مستشار </h3>
                        </div>

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                <form class=" g-3" method="post" action="{{route('admin_panel.advisors.store')}}" enctype="multipart/form-data" >
                                    @method('POST')
                                    @csrf
                                    @if ($errors->any())

                                        <div class="alert alert-danger">

                                            <ul style="list-style: none;margin:0">

                                                @foreach ($errors->all() as $error)

                                                    <li>{{ $error }}</li>

                                                @endforeach

                                            </ul>

                                        </div>

                                    @endif
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label for="inputAddress" class="form-label"> الصورة الشخصية </label>
                                            <input type="file" class="form-control"  placeholder="1234 Main St" name="personal_image">
                                        </div>

                                        <div class="col-md-6">
                                            <label for="inputEmail4" class="form-label">الاسم </label>
                                            <input type="text" class="form-control"   name="name">
                                        </div>

                                        <div class="col-md-6">
                                            <label for="inputEmail4" class="form-label">رقم الجوال</label>
                                            <input type="tel" class="form-control"   name="mobile">
                                        </div>
                                        <div class="col-md-6">
                                            <label for="inputEmail4" class="form-label"> الاستشارة </label>
                                            <input type="text" class="form-control"   name="description">
                                        </div>


                                        <div class="col-6">
                                            <div class="text-center">
                                            <button type="submit" class="btn btn-primary">إضافة </button>
                                            </div>
                                        </div>

                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/advisors/edit.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"المستشارين</li>
                                    <li class="breadcrumb-item active"> تعديل </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->
        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class="">تعديل معلومات المستشار</h3>
                        </div>

                        <div class="" style="padding: 2%;">
                            <div class="container">
                                <form class=" g-3" method="post" action="{{route('admin_panel.advisors.update',$advisor->id)}}" enctype="multipart/form-data" >
                                    @method('PATCH')
                                    @csrf
                                    @if ($errors->any())

                                        <div class="alert alert-danger">

                                            <ul style="list-style: none;margin:0">

                                                @foreach ($errors->all() as $error)

                                                    <li>{{ $error }}</li>

                                                @endforeach

                                            </ul>

                                        </div>

                                    @endif
                                    <div class="col-md-6 ">
{{--                                        <label for="inputAddress" class="form-label"> الصورة الشخصية </label>--}}
                                        <img alt="avatar" src="/{{$advisor->personal_image}}"  width="200" height="200"/>
                                        <br><br>
                                        <input type="file" class="form-control"  placeholder="1234 Main St" name="personal_image">
                                    </div>



                                    <div class="col-md-6">

                                    </div>

                                    <div class="col-md-6">
                                        <label for="inputEmail4" class="form-label">رقم الجوال</label>
                                        <input type="tel" class="form-control"  value="{{$advisor->mobile}}" name="mobile">
                                    </div>
                                    <div class="col-md-6">

                                    </div>
                                    <div class="col-md-6">
                                        <label for="inputEmail4" class="form-label">الاسم </label>
                                        <input type="text" class="form-control"  value="{{$advisor->name}}" name="name">
                                    </div>
                                    <div class="col-md-6">

                                    </div>
                                    <div class="col-md-6">
                                        <label for="inputEmail4" class="form-label"> الاستشارة </label>
                                        <input type="text" class="form-control"  value="{{$advisor->description}}" name="description">
                                    </div>
                                    <div class="col-6">
                                        <div class="text-center">
                                        <button type="submit" class="btn btn-primary">تعديل</button>
                                        </div>
                                    </div>


                                </form>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->

    </div>



@endsection

resources/views/admin/advisors/item.blade.php
@extends('admin.dashboard')

@section('content')

    <div id="content" class="main-content">
        <!--  BEGIN BREADCRUMBS  -->
        <div class="secondary-nav">
            <div class="breadcrumbs-container" data-page-heading="Analytics">
                <header class="header navbar navbar-expand-sm">
                    <a href="javascript:void(0);" class="btn-toggle sidebarCollapse" data-placement="bottom">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-menu"><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
                    </a>
                    <div class="d-flex breadcrumb-content">
                        <div class="page-header">

                            <div class="page-title">
                            </div>

                            <nav class="breadcrumb-style-one" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"المستشارين</li>
                                    <li class="breadcrumb-item active"> عرض المستشار </li>
                                </ol>
                            </nav>

                        </div>
                    </div>
                </header>
            </div>
        </div>
        <br>
        <!--  END BREADCRUMBS  -->

        <div class="row layout-spacing " >

            <!-- Content -->
            <div class="col-12" style="margin:2% 2% auto;">
                <div class="user-profile ">
                    <div class="widget-content widget-content-area">
                        <div class=" " style="padding:2% 2% 0px; " >
                            <h3 class=""> معلومات المستشار</h3>
                          </div>
                        <div class="" style="padding: 2%; font-weight: bold;">
                            <div class="container">

                                <div class="col-md-6 ">
                                    {{--                                        <label for="inputAddress" class="form-label "> الصورة الشخصية </label>--}}
                                    <img alt="avatar" src="/{{$advisor->personal_image}}"  width="200" height="200"/>
                                    <br><br>
                                </div>
                                <div class="col-md-6">
                                    <label  >الاسم : </label>
                                    <span>{{$advisor->name}}</span>
                                </div>
                                <div class="col-md-6">
                                    <label >رقم الجوال : </label>
                                    <span>{{$advisor->mobile}}</span>
                                </div>
                                <div class="col-md-6" >
                                     <label  > الاستشارة : </label>
                                    <span>{{$advisor->description}}</span>
                                </div>
                            </div>

                        </div>

                        </div>
                    </div>
                </div>
            </div>




{{--        <div class="container">--}}

{{--            <div class="col-md-6">--}}
{{--                <div class="col-md-6">--}}
{{--                    <label for="inputAddress" class="form-label"> الصورة الشخصية </label>--}}
{{--                    <img alt="avatar" src="/{{$advisor->personal_image}}"  width="200" height="200"/>--}}
{{--                    <br><br>--}}
{{--                </div>--}}


{{--                <div class="col-md-6">--}}
{{--                    <label for="inputEmail4" class="form-label">رقم الجوال</label>--}}
{{--                    <p>{{$advisor->mobile}}</p>--}}
{{--                </div>--}}

{{--                <div class="col-md-6">--}}
{{--                    <label for="inputEmail4" class="form-label">الاسم </label>--}}
{{--                    <p>{{$advisor->name}}</p>--}}
{{--                </div>--}}
{{--                <div class="col-md-6">--}}
{{--                    <label for="inputState" class="form-label"> الاستشارة </label>--}}
{{--                    <p>{{$advisor->description}}</p>--}}
{{--                </div>--}}
{{--            </div>--}}

{{--        </div>--}}
        <!--  BEGIN FOOTER  -->
    @include('admin.layouts.footer')
    <!--  END FOOTER  -->
    </div>



@endsection