routes/web.php
<?php

use App\Http\Controllers\Admin_Panel\AuthController;
use App\Models\Admin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth:admin'])->name('dashboard');

//
//require __DIR__.'/auth.php';
//Route::get('/clear-cache', function() {
//    $exitCode = Artisan::call('cache:clear');
//    // return what you want
//});
/*
|--------------------------------------------------------------------------
| Admin Authentication
|--------------------------------------------------------------------------
*/


Route::group(['prefix' => 'admin_panel','as' => 'admin_panel.'], function () {
//    Route::post('/register', [AuthController::class, 'register']);
    Route::get('/login_view', [AuthController::class, 'loginView'])->name('login');
    Route::post('/login', [AuthController::class, 'login']);

    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('/', [AuthController::class, 'analys']);
        Route::resource('profile', AuthController::class);
        Route::get('/edit_password', [AuthController::class, 'editPassword']);
        Route::post('/update_password', [AuthController::class, 'updatePassword']);
        Route::get('/logout', [AuthController::class, 'logout']);

        ## Resturant Routes
        Route::resource('resturants', \App\Http\Controllers\Admin_Panel\ResturantController::class);
        Route::get('/resturant_del/{id}', [\App\Http\Controllers\Admin_Panel\ResturantController::class, 'destroy']);
        Route::get('/search_resturant/{id}',[\App\Http\Controllers\Admin_Panel\ResturantController::class,'search']);
        Route::get('/reject/{id}',[\App\Http\Controllers\Admin_Panel\ResturantController::class,'reject']);
        Route::get('/accept/{id}',[\App\Http\Controllers\Admin_Panel\ResturantController::class,'accept']);


        ## Representative Routes
        Route::resource('representatives', \App\Http\Controllers\Admin_Panel\RepresentativeController::class);
        Route::get('/representative_del/{id}', [\App\Http\Controllers\Admin_Panel\RepresentativeController::class, 'destroy']);
        Route::get('/search_representative',[\App\Http\Controllers\Admin_Panel\RepresentativeController::class,'search']);

        ## Client Routes
        Route::resource('clients', \App\Http\Controllers\Admin_Panel\ClientController::class);
        Route::get('/client_del/{id}', [\App\Http\Controllers\Admin_Panel\ClientController::class, 'destroy']);
        Route::get('/client_orders/{id}', [\App\Http\Controllers\Admin_Panel\ClientController::class, 'orders']);
        Route::get('/client_rates/{id}', [\App\Http\Controllers\Admin_Panel\ClientController::class, 'rates']);
        Route::get('/search_client',[\App\Http\Controllers\Admin_Panel\ClientController::class,'search']);

        ## Advisor Routes
        Route::resource('advisors', \App\Http\Controllers\Admin_Panel\AdvisorController::class);
        Route::get('/advisor_del/{id}', [\App\Http\Controllers\Admin_Panel\AdvisorController::class, 'destroy']);
        Route::get('/search_advisor',[\App\Http\Controllers\Admin_Panel\AdvisorController::class,'search']);

        ## Setting Routes
        Route::resource('settings', \App\Http\Controllers\Admin_Panel\SettingController::class);

        ## Coupon Routes
        Route::resource('coupons', \App\Http\Controllers\Admin_Panel\CouponController::class);
        Route::get('/coupon_del/{id}', [\App\Http\Controllers\Admin_Panel\CouponController::class, 'destroy']);
        Route::get('/search_coupon',[\App\Http\Controllers\Admin_Panel\CouponController::class,'search']);

        ## Meal Types Routes
        Route::resource('meal_types', \App\Http\Controllers\Admin_Panel\MealTypeController::class);
        Route::get('/meal_type_del/{id}', [\App\Http\Controllers\Admin_Panel\MealTypeController::class, 'destroy']);
        Route::get('/search_meal_type',[\App\Http\Controllers\Admin_Panel\MealTypeController::class,'search']);
        Route::get('/reject_meal_type/{id}',[\App\Http\Controllers\Admin_Panel\MealTypeController::class,'reject']);
        Route::get('/accept_meal_type/{id}',[\App\Http\Controllers\Admin_Panel\MealTypeController::class,'accept']);

    });
});


Route::get('/token', function () {
    return csrf_token();
});

resources/views/admin/layouts/footer.blade.php
<!--  BEGIN FOOTER  -->
<div class="footer-wrapper">
    <div class="footer-section f-section-1">
        <p class="">Copyright © <span class="dynamic-year">2022</span> <a target="_blank" href="https://designreset.com/cork-admin/">DesignReset</a>, All rights reserved.</p>
    </div>
    <div class="footer-section f-section-2">
        <p class="">Coded with <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg></p>
    </div>
</div>
<!--  END FOOTER  -->

resources/views/admin/layouts/scripts.blade.php
<!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
<script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('js/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('js/mousetrap.min.js') }}"></script>
<script src="{{ asset('js/waves.min.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
<!-- END GLOBAL MANDATORY SCRIPTS -->

<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
<script src="{{ asset('js/apexcharts.min.js') }}"></script>
<script src="{{ asset('js/dash_1.js') }}"></script>
<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->



{{--<script src="{{asset('js/custom.js')}}"></script>--}}
<!-- END GLOBAL MANDATORY SCRIPTS -->

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{{asset('js/datatables.js')}}"></script>

<!-- Table -->
<script src="{{asset('js/table/vendors.min.js')}}"></script>
<script src="{{asset('js/table/highlight.pack.js')}}"></script>
<script src="{{asset('js/table/custom.js')}}"></script>

<script src="{{asset('js/table/scrollspyNav.js')}}"></script>
<script src="{{asset('js/scrollspyNav.js')}}"></script>

<script>
    checkall('checkbox_parent_all', 'checkbox_child');
    checkall('hover_parent_all', 'hover_child');
    checkall('striped_parent_all', 'striped_child');
    checkall('bordered_parent_all', 'bordered_child');
    checkall('mixed_parent_all', 'mixed_child');
    checkall('noSpacing_parent_all', 'noSpacing_child');
    checkall('custom_mixed_parent_all', 'custom_mixed_child');
</script>

{{--<script src="../src/plugins/src/highlight/highlight.pack.js"></script>--}}
{{--<!-- END GLOBAL MANDATORY STYLES -->--}}
{{--<script src="../src/assets/js/scrollspyNav.js"></script>--}}
<script src="{{asset('splide/splide.min.js')}}"></script>
<script src="{{asset('splide/custom-splide.js')}}"></script>

resources/views/admin/layouts/sidebar.blade.php
<!--  BEGIN SIDEBAR  -->
<div class="sidebar-wrapper sidebar-theme">

    <nav id="sidebar">

{{--        <div class="navbar-nav theme-brand flex-row  text-center">--}}
{{--            <div class="nav-logo">--}}
{{--                <div class="nav-item theme-logo">--}}
{{--                    <a href="./index.html">--}}
{{--                        <img src="{{ asset('src/assets/img/logo..svg') }}" class="navbar-logo" alt="logo">--}}
{{--                    </a>--}}
{{--                </div>--}}
{{--                <div class="nav-item theme-text">--}}
{{--                    <a href="./index.html" class="nav-link"> CORK </a>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--            <div class="nav-item sidebar-toggle">--}}
{{--                <div class="btn-toggle sidebarCollapse">--}}
{{--                    <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevrons-left"><polyline points="11 17 6 12 11 7"></polyline><polyline points="18 17 13 12 18 7"></polyline></svg>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
        <div class="shadow-bottom"></div>
        <ul class="list-unstyled menu-categories" id="accordionExample">

          <li class="menu {{ (request()->is('/admin_panel')) ? 'active' : '' }}">
                <a href="#dashboard" data-bs-toggle="collapse" aria-expanded="true" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                        <span>لوحة التحكم</span>
                    </div>
                    <div>
                        <svg xmlns="http://www.w3.org/2000/.svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg>
                    </div>
                </a>
                <ul class="collapse submenu list-unstyled show" id="dashboard" data-bs-parent="#accordionExample">
                    <li class="{{ (request()->is('/admin_panel')) ? 'active' : '' }}">
                        <a href="/admin_panel"> المخططات </a>
                    </li>
                </ul>
            </li>

            <li class="menu {{ (request()->is('*/resturants*')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.resturants.index')}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-coffee"><path d="M18 8h1a4 4 0 0 1 0 8h-1"></path><path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"></path><line x1="6" y1="1" x2="6" y2="4"></line><line x1="10" y1="1" x2="10" y2="4"></line><line x1="14" y1="1" x2="14" y2="4"></line></svg>
                        <span>المطاعم</span>
                    </div>
                </a>
            </li>
            <li class="menu {{ (request()->is('*/representatives*')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.representatives.index')}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-truck"><rect x="1" y="3" width="15" height="13"></rect><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"></polygon><circle cx="5.5" cy="18.5" r="2.5"></circle><circle cx="18.5" cy="18.5" r="2.5"></circle></svg>
                        <span>المندوبين </span>
                    </div>
                </a>
            </li>
            <li class="menu {{ (request()->is('*/clients*')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.clients.index')}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                        <span>العملاء </span>
                    </div>
                </a>
            </li>
            <li class="menu {{ (request()->is('*/advisors*')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.advisors.index')}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-book-open"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"></path><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"></path></svg>
                        <span>المستشارين </span>
                    </div>
                </a>
            </li>
            <li class="menu {{ (request()->is('*/coupons*')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.coupons.index')}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-gift"><polyline points="20 12 20 22 4 22 4 12"></polyline><rect x="2" y="7" width="20" height="5"></rect><line x1="12" y1="22" x2="12" y2="7"></line><path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"></path><path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"></path></svg>
                        <span>أكواد الحسم </span>
                    </div>
                </a>
            </li>
            <li class="menu {{ (request()->is('*/settings')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.settings.index')}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-settings"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>
                         <span>الإعدادات </span>
                    </div>
                </a>
            </li>

            <li class="menu {{ (request()->is('*/meal_types')) ? 'active' : '' }}">
                <a href="{{route('admin_panel.meal_types.index')}}" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-briefcase"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"></path></svg>
                        <span>تصنيفات الوجبات </span>
                    </div>
                </a>
            </li>




        </ul>

    </nav>

</div>
<!--  END SIDEBAR  -->

resources/views/admin/layouts/topHeader.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <title>Diet </title>
    <link rel="icon" type="image/x-icon" href="{{ asset('src/assets/img/diet_logo.jpg') }}"/>
    <link href="{{ asset('css/light/loader.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/dark/loader.css') }}" rel="stylesheet" type="text/css" />
    <script src="{{ asset('js/loader.js') }}"></script>

    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;1000&family=Noto+Sans+Arabic:wght@300&display=swap" rel="stylesheet">

    <link href="{{ asset('css/bootstrap.rtl.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/light/plugins.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/dark/plugins.css') }}" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->

    <!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM STYLES -->
    <link href="{{ asset('css/apexcharts.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/light/dash_1.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/dark/dashboard/dash_1.css') }}" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS/CUSTOM STYLES -->

    <!-- Tables -->
    <link rel="stylesheet" type="text/css" href="{{asset('css/datatables.css')}}">

    <link rel="stylesheet" type="text/css" href="{{asset('css/light/table/scrollspyNav.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/dark/table/scrollspyNav.css')}}">


    <link rel="stylesheet" type="text/css" href="{{asset('css/light/table/dt-global_style.css')}}">
{{--    <link rel="stylesheet" type="text/css" href="{{asset('css/light/table/custom_dt_custom.css')}}">--}}

    <link rel="stylesheet" type="text/css" href="{{asset('css/dark/table/dt-global_style.css')}}">
{{--    <link rel="stylesheet" type="text/css" href="{{asset('css/dark/table/custom_dt_custom.css')}}">--}}


    <link rel="stylesheet" type="text/css" href="{{asset('splide/splide.min.css')}}">

{{--    <link rel="stylesheet" type="text/css" href="../src/assets/css/light/scrollspyNav.css" />--}}
    <link rel="stylesheet" type="text/css" href="{{asset('css/light/splide/custom-splide.min.css')}}">

{{--    <link rel="stylesheet" type="text/css" href="../src/assets/css/dark/scrollspyNav.css" />--}}
    <link rel="stylesheet" type="text/css" href="{{asset('css/dark/splide/custom-splide.min.css')}}">

    <!--  BEGIN CUSTOM STYLE PROFILE  -->
    <link href="{{asset('css/light/profile/list-group.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('css/light/profile/user-profile.css')}}" rel="stylesheet" type="text/css" />

    <link href="{{asset('css/dark/profile/list-group.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('css/dark/profile/user-profile.css')}}" rel="stylesheet" type="text/css" />
    <!--  END CUSTOM STYLE PROFILE  -->

    <!--  BEGIN CUSTOM STYLE AJAX SEARCH  -->
{{--    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">--}}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <!--  END CUSTOM STYLE AJAX SEARCH  -->

    <style>
        form div{
            margin: 15px;
        }
    </style>


</head>